//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMGA.Administrador {
    
    
    public partial class TipoElementos {
        
        /// <summary>
        /// uc_TipoElemento1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIMGA.Controles.Administrador.uc_TipoElemento uc_TipoElemento1;
    }
}
